"""harden_schema_enums_numeric_indexes_position

Revision ID: 1b3e415de881
Revises: 48bc3c91ee8a
Create Date: 2026-02-27 10:54:25.085694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3e415de881'
down_revision: Union[str, Sequence[str], None] = '48bc3c91ee8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create PostgreSQL ENUM types before they are used (idempotent: skip if exists)
    for name, values in [
        ("contract_type_enum", "('PERPETUAL', 'FUTURES')"),
        ("order_side_enum", "('BUY', 'SELL')"),
        ("order_type_enum", "('LIMIT', 'MARKET')"),
        ("order_status_enum", "('OPEN', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED')"),
        ("margin_mode_enum", "('CROSS', 'ISOLATED')"),
        ("taker_side_enum", "('BUY', 'SELL')"),
        ("position_side_enum", "('LONG', 'SHORT')"),
    ]:
        op.execute(
            f"DO $$ BEGIN CREATE TYPE {name} AS ENUM {values}; "
            "EXCEPTION WHEN duplicate_object THEN NULL; END $$"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    # Create positions with raw SQL so we don't trigger SQLAlchemy's Enum.create() (type already exists)
    op.execute("""
        CREATE TABLE positions (
            id UUID NOT NULL,
            user_id UUID NOT NULL,
            instrument_id UUID NOT NULL,
            side position_side_enum NOT NULL,
            quantity NUMERIC(20, 8) NOT NULL,
            entry_price NUMERIC(20, 8) NOT NULL,
            leverage NUMERIC(5, 2) NOT NULL,
            unrealized_pnl NUMERIC(20, 8) NOT NULL DEFAULT 0,
            liquidation_price NUMERIC(20, 8) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT now(),
            updated_at TIMESTAMP NOT NULL DEFAULT now(),
            PRIMARY KEY (id),
            FOREIGN KEY (instrument_id) REFERENCES instruments (id),
            FOREIGN KEY (user_id) REFERENCES users (id),
            UNIQUE (user_id, instrument_id, side)
        )
    """)
    op.add_column('instruments', sa.Column('created_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.add_column('instruments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.alter_column('instruments', 'contract_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PERPETUAL', 'FUTURES', name='contract_type_enum', create_type=False),
               existing_nullable=False)
    op.alter_column('instruments', 'tick_size',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('instruments', 'max_leverage',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('instruments', 'maintenance_margin_rate',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=False)
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.alter_column('orders', 'side',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('BUY', 'SELL', name='order_side_enum', create_type=False),
               existing_nullable=False)
    op.alter_column('orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LIMIT', 'MARKET', name='order_type_enum', create_type=False),
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('orders', 'filled_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED', name='order_status_enum', create_type=False),
               existing_nullable=False)
    op.alter_column('orders', 'leverage',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'margin_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CROSS', 'ISOLATED', name='margin_mode_enum', create_type=False),
               existing_nullable=False)
    op.create_index('idx_orders_instrument_status', 'orders', ['instrument_id', 'status'], unique=False)
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.add_column('trades', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.alter_column('trades', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('trades', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('trades', 'taker_side',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('BUY', 'SELL', name='taker_side_enum', create_type=False),
               existing_nullable=False)
    op.create_index('idx_trades_instrument_id', 'trades', ['instrument_id'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.add_column('wallets', sa.Column('created_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.add_column('wallets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.alter_column('wallets', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('wallets', 'available_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'available_balance',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('wallets', 'updated_at')
    op.drop_column('wallets', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_index('idx_trades_instrument_id', table_name='trades')
    op.alter_column('trades', 'taker_side',
               existing_type=sa.Enum('BUY', 'SELL', name='taker_side_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('trades', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('trades', 'price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('trades', 'updated_at')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_index('idx_orders_instrument_status', table_name='orders')
    op.alter_column('orders', 'margin_mode',
               existing_type=sa.Enum('CROSS', 'ISOLATED', name='margin_mode_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'leverage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('OPEN', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED', name='order_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'filled_quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('orders', 'order_type',
               existing_type=sa.Enum('LIMIT', 'MARKET', name='order_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'side',
               existing_type=sa.Enum('BUY', 'SELL', name='order_side_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('orders', 'updated_at')
    op.alter_column('instruments', 'maintenance_margin_rate',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('instruments', 'max_leverage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('instruments', 'tick_size',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('instruments', 'contract_type',
               existing_type=sa.Enum('PERPETUAL', 'FUTURES', name='contract_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('instruments', 'updated_at')
    op.drop_column('instruments', 'created_at')
    op.drop_table('positions')

    # Drop PostgreSQL ENUM types (order can matter if any depend on another)
    op.execute("DROP TYPE IF EXISTS contract_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS order_side_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS order_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS order_status_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS margin_mode_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS taker_side_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS position_side_enum CASCADE")
    # ### end Alembic commands ###
